#!/bin/sh

for i in $(awk -F: '$3 >= 1000 {print $3}' /etc/passwd); do
    mkdir -p /run/user/"$i"
    chown "$i:$i" /run/user/"$i"    # added group ownership
    chmod 700 /run/user/"$i"
done

sv once xdg-run-generator