#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
export SCRIPT_DIR

# shellcheck source=includes/install_system
source "$SCRIPT_DIR/includes/install_system"

# shellcheck source=includes/utils
source "$SCRIPT_DIR/includes/utils"

# shellcheck source=includes/common
source "$SCRIPT_DIR/includes/common"

args=("$@")

for ((i=0; i<${#args[@]}; i++)); do
  arg="${args[$i]}"
  case "$arg" in
  --handle_internet_connection)
    if ! handle_internet_connection; then
      exit 1
    fi
    exit 0
    ;;
  --help)
    echo "Usage: $0 [--handle_internet_connection]"
    exit 0
    ;;
  *)
    echo "Unknown option: $arg"
    exit 1
    ;;
  esac
done

install_system