#!/bin/sh

# Source environment variables if available
[ -d "$TURNSTILE_ENV_DIR" ] && exec chpst -e "$TURNSTILE_ENV_DIR" onedrive --monitor --verbose

# Fallback if no environment directory
exec onedrive --monitor --verbose
