#!/bin/bash

setup_base_system() {
  echo 'Installing base system...' >&2
  x_chroot /mnt /bin/bash -c "
    if ! xbps-install -Suy xbps; then
      echo 'Failed to update xbps' >&2
      exit 1
    fi
    if ! xbps-install -uy; then
      echo 'Failed to update system' >&2
      exit 1
    fi
    if ! xbps-install -y base-system; then
      echo 'Failed to install base-system' >&2
      exit 1
    fi
    if ! xbps-remove -y base-container-full; then
      echo 'Failed to remove base-container-full' >&2
      exit 1
    fi
    if ! xbps-install -y fontconfig; then
      echo 'Failed to install fontconfig' >&2
      exit 1
    fi
    if ! xbps-reconfigure -fa; then
      echo 'xbps-reconfigure failed' >&2
      exit 1
    fi
  "
}

setup_bootloader() {
  local boot_mode="$1"

  echo 'Installing bootloader...' >&2
  x_chroot /mnt /bin/bash -c "
    echo 'Preparing grub...'
    if ! install_grub '${boot_mode}'; then
      echo 'Grub installation failed' >&2
      exit 1
    fi
  "
}

update_xbps_repo() {
  echo 'Installing nonfree/multilib repositories...' >&2
  x_chroot /mnt /bin/bash -c "
    if ! xbps-install -Sy void-repo-nonfree void-repo-multilib{,-nonfree}; then
      echo 'Failed to install extra repositories' >&2
      exit 1
    fi
    if ! xbps-install -Su; then
      echo 'Failed to update system after adding repositories' >&2
      exit 1
    fi
  "
}

setup_pyenv() {
  local username="$1"

  echo 'Installing pyenv...' >&2
  x_chroot /mnt /bin/bash -c "
    su - '${username}' -c 'curl -fsSL https://pyenv.run | bash'

    echo 'export PYENV_ROOT=\"\$HOME/.pyenv\"' >> '/home/${username}/.bash_profile'
    echo '[[ -d \$PYENV_ROOT/bin ]] && export PATH=\"\$PYENV_ROOT/bin:\$PATH\"' >> '/home/${username}/.bash_profile'
    echo 'eval \"\$(pyenv init - bash)\"' >> '/home/${username}/.bash_profile'

    chown -R '${username}:${username}' '/home/${username}/.pyenv'
  "
}

setup_pipewire() {
  echo 'Setting up PipeWire...' >&2
  x_chroot /mnt /bin/bash -c "
    if ! mkdir -p /etc/pipewire/pipewire.conf.d; then
      echo 'Failed to create pipewire folder' >&2
    fi
    if ! ln -sv /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/; then
      echo 'WirePlumber configuration failed to link' >&2
    fi
    if ! ln -sv /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/; then
      echo 'Pipewire configuration failed to link' >&2
    fi
    if ! mkdir -p /etc/alsa/conf.d; then
      echo 'Failed to create alsa config directory' >&2
    fi
    if ! ln -sv /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/; then
      echo 'Failed to link ALSA pipewire config' >&2
    fi
    if ! ln -sv /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/; then
      echo 'Failed to link ALSA pipewire default config' >&2
    fi
  "
}


setup_users() {
  local username="$1"
  local password="$2"

  echo 'Setting up users...' >&2
  x_chroot /mnt /bin/bash -c "
    echo 'root:${password}' | chpasswd -c SHA512
    echo 'Setting up new user...' >&2
    useradd -m '${username}'
    echo '${username}:${password}' | chpasswd -c SHA512
    usermod -aG wheel,audio,video '${username}'
    sed -i '/^#\s*%wheel ALL=(ALL:ALL) ALL/s/^# //' /etc/sudoers
  "
}

setup_services() {
  echo 'Enabling services...' >&2
  x_chroot /mnt /bin/bash -c "
    for svc in dbus bluetoothd sddm NetworkManager chronyd rtkit polkitd; do
      if ! service -c /etc/runit/runsvdir/default/ \$svc; then
        echo \"Warning: Failed to enable \$svc\" >&2
      fi
    done
  "
}

setup_nnn() {
  local username="$1"

  echo 'Installing nnn plugins...' >&2
  x_chroot /mnt /bin/bash -c "
    su - '${username}' -c 'curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh'
  "
}

setup_bashrc() {
  local username="$1"

  echo 'Configuring bashrc...' >&2
  x_chroot /mnt /bin/bash -c "
    echo \"bind 'set enable-bracketed-paste off'\" >> '/home/${username}/.bashrc'

    echo 'export EDITOR=/bin/nvim' >> '/home/${username}/.bash_profile'
    echo '[[ -f \$HOME/.bashrc ]] && . \$HOME/.bashrc' >> '/home/${username}/.bash_profile'
  "
}


setup_nvm() {
  local username="$1"

  echo 'Installing nvm...' >&2
  x_chroot /mnt /bin/bash -c "
    su - '${username}' -c 'PROFILE=/home/${username}/.bashrc curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash'
  "
}

setup_kde_defaults() {
  local username="$1"

  echo 'Configuring KDE defaults...' >&2
  x_chroot /mnt /bin/bash -c "
    mkdir -p '/home/${username}/.config'
    mkdir -p '/home/${username}/.config/autostart/'
    ln -s /usr/share/applications/pipewire.desktop '/home/${username}/.config/autostart/'

    echo '[General]' >> '/home/${username}/.config/kdeglobals'
    echo 'TerminalApplication=alacritty' >> '/home/${username}/.config/kdeglobals'
    echo 'TerminalService=' >> '/home/${username}/.config/kdeglobals'
    echo 'BrowserApplication=!dolphin.desktop' >> '/home/${username}/.config/kdeglobals'
  "
}

set_home_permissions() {
  local username="$1"

  echo 'Fixing home directory permissions...' >&2
  x_chroot /mnt /bin/bash -c "
    chown -R '${username}:${username}' '/home/${username}'
    chmod -R u+rw '/home/${username}/.config'
  "
}


copy_configs(){
  local user_home="$1"
  local user_name="$2"

  mkdir -p "$user_home/.config"
  cp -rv "$SCRIPT_DIR"/../config/* "$user_home/.config/"

  x_chroot /mnt /bin/bash -c "
    if ! chown -R '${user_name}:${user_name}' '/home/${user_name}'; then
      echo 'Failed to chown /home/${user_name}' >&2
      return 1
    fi
  "
}

setup_nvidia() {
  echo 'Checking for NVIDIA GPU...' >&2
  if ! lspci | grep -qi nvidia; then
    echo 'No NVIDIA GPU detected, skipping...' >&2
    return 0
  fi

  echo 'NVIDIA GPU detected, installing drivers...' >&2
  x_chroot /mnt /bin/bash -c "
    if ! xbps-install -y nvidia; then
      echo 'Failed to install nvidia drivers' >&2
      exit 1
    fi
  "
}