#!/bin/bash
function copy_scripts() {
  local script_file_names
  readarray -t script_file_names < <(find "$SCRIPT_DIR"/scripts -type f -printf '%f\n')

  for f in "${script_file_names[@]}"; do
    cp -rv "$SCRIPT_DIR/scripts/$f" "/bin/$f"
    chmod 755 "/bin/$f"
  done

  mkdir -p /usr/lib/psi/
  cp -rv "$SCRIPT_DIR"/includes/utils /usr/lib/psi/utils
  cp -rv "$SCRIPT_DIR"/includes/service /usr/lib/psi/service
  chmod -R 755 /usr/lib/psi
}