#!/bin/bash
# shellcheck source=utils
source "$SCRIPT_DIR/includes/utils"

function copy_bin() {
    if ! sudo cp -rfvT "$SCRIPT_DIR"/files/scripts/ /bin/; then
        echo "Failed to copy scripts to /bin/" >&2
        return 1
    fi
}
export -f copy_bin


function copy_configs(){
  local user_home=$1
  local user_name=$2
  mkdir -p "$user_home"/.config
  cp -rv "$SCRIPT_DIR"/../config/* "$user_home"/.config/
  export user_name
  x_chroot /mnt /bin/bash -c  "
    if ! chown -R \"\$user_name:\$user_name\" \"/home/\$user_name\"; then
      echo \"Failed to chown /home/\$user_name\" >&2
      return 1
    fi
  "
}
export -f copy_configs

function copy_wpa_supplicant_conf(){
  local src=/etc/wpa_supplicant/wpa_supplicant.conf
  local dst=/mnt/etc/wpa_supplicant/wpa_supplicant.conf
  if [[ ! -f "$src" ]]; then
    echo "no wpa config in $src" >&2
    return 1
  fi

  # Create target directory if it doesn't exist
  mkdir -p /mnt/etc/wpa_supplicant/

  if ! cp -v "$src" "$dst"; then
    echo "Failed to copy wpa_supplicant.conf" >&2
    return 2
  fi
}
export -f copy_wpa_supplicant_conf