#!/bin/bash
# shellcheck source=utils
source "$SCRIPT_DIR/includes/utils"

function copy_bin() {
    if ! sudo cp -rfvT "$SCRIPT_DIR"/files/scripts/ /bin/; then
        echo "Failed to copy scripts to /bin/" >&2
        return 1
    fi
}
export -f copy_bin


function copy_wayfire_ini(){
  local user_home=$1
  mkdir -p "$user_home"/.config
  cp -v "$SCRIPT_DIR"/../config/wayfire.ini "$user_home"/.config/wayfire.ini
}
export -f copy_wayfire_ini

function copy_wpa_supplicant_conf(){
  local src=/etc/wpa_supplicant/wpa_supplicant.conf
  local dst=/mnt/etc/wpa_supplicant/wpa_supplicant.conf
  if [[ ! -f "$src" ]]; then
    echo "no wpa config in $src" >&2
    return 1
  fi

  # Create target directory if it doesn't exist
  mkdir -p /mnt/etc/wpa_supplicant/

  if ! cp -v "$src" "$dst"; then
    echo "Failed to copy wpa_supplicant.conf" >&2
    return 2
  fi
}
export -f copy_wpa_supplicant_conf

# Copy cappuccino rofi theme
function copy_rofi_usr_theme(){
  # .config part will be copied along with everything else later
  if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/usr/share/rofi/themes/ /usr/share/rofi/themes/; then
    echo "Failed to copy rofi theme to /usr/share/rofi/themes/" >&2
    return 1
  fi
}
export -f copy_rofi_usr_theme

function copy_dots(){
  if ! sudo cp -rfvT "$SCRIPT_DIR"/files/system/.config/ "$HOME"/.config/; then
    echo "Failed to copy dotfiles to $HOME/.config/" >&2
    return 1
  fi

  if ! sudo chown -R "$USER" "$HOME"/.config/; then
    echo "Failed to chown $HOME/.config/" >&2
    return 1
  fi

  if ! sudo cp -rfv "$SCRIPT_DIR"/files/system/.config/ /etc/skel/; then
    echo "Failed to copy dotfiles to /etc/skel" >&2
    return 1
  fi
}
export -f copy_dots