#!/bin/bash

function export_package_group(){
  local group_name
  local list_name
  local clean_package_list
  group_name=$1
  list_name=$2

  clean_package_list=$(sed -E 's/(( *)#.*$)|(^( |	)+$)//' < "$SCRIPT_DIR"/../packages/"$list_name".lst | sed '/^[[:space:]]*$/d')
  echo "$clean_package_list" | awk "/^\[$group_name\]/{read=1;next}/\\[/{read=0}read && NF{print}"
}
export -f export_package_group

function install_xbps_packages() {
  local group_name
  local package_list=("$@")
  if ! xbps-install -y "${package_list[@]}"; then
    echo "Failed to install packages from group $group_name" >&2
    return 1
  fi
}
export -f install_xbps_packages
